// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 用户表
type Account struct {
	// 主键:用户ID
	ID                int64              `db:"id" json:"id"`
	Phone             pgtype.Text        `db:"phone" json:"phone"`
	Email             pgtype.Text        `db:"email" json:"email"`
	Username          pgtype.Text        `db:"username" json:"username"`
	Nickname          pgtype.Text        `db:"nickname" json:"nickname"`
	Password          pgtype.Text        `db:"password" json:"password"`
	PasswordSalt      pgtype.Text        `db:"password_salt" json:"passwordSalt"`
	PasswordUpdatedAt pgtype.Timestamptz `db:"password_updated_at" json:"passwordUpdatedAt"`
	CreatedBy         pgtype.Int8        `db:"created_by" json:"createdBy"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	UpdatedBy         pgtype.Int8        `db:"updated_by" json:"updatedBy"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updatedAt"`
	DeletedBy         pgtype.Int8        `db:"deleted_by" json:"deletedBy"`
	DeletedAt         pgtype.Timestamptz `db:"deleted_at" json:"deletedAt"`
}

// 用户登录session记录表
type Session struct {
	// 主键:session_id
	ID pgtype.UUID `db:"id" json:"id"`
	// 外键:public.accounts.id
	Uid          int64              `db:"uid" json:"uid"`
	ClientIp     string             `db:"client_ip" json:"clientIp"`
	UserAgent    string             `db:"user_agent" json:"userAgent"`
	IsBlocked    bool               `db:"is_blocked" json:"isBlocked"`
	RefreshToken string             `db:"refresh_token" json:"refreshToken"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}
