// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dao

import (
	"context"
)

type Querier interface {
	// CreateAccount: 创建用户
	// table: accounts
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	// UpdateAccount: 更新用户 (非空表达式实现动态传参更新数据)
	// table: accounts
	//  NOTICE: COALESCE返回表达式中第一个非空表达式(例如: COALESCE(NULL, NULL, 1, 2) 返回 1) -  缺点就是更新时不能设置为null值
	//  [nullable-parameters](https://docs.sqlc.dev/en/latest/howto/named_parameters.html#nullable-parameters)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
